language: elixir
sudo: false
otp_release:
  - 17.4
  - 17.5
  - 18.0
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report

