language: elixir
sudo: false
elixir:
  - 1.4.5
  - 1.5.0-rc.0
otp_release:
  - 18.3
  - 19.3
  - 20.0
script:
  - mix test
  - mix credo --strict
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
