language: elixir
sudo: false
elixir:
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
otp_release:
  - 18.0
  - 18.1
  - 18.2
  - 19.0
  - 19.1
after_success:
  - "mix compile && mix coveralls.travis"
after_script:
  - MIX_ENV=docs mix deps.get
  - MIX_ENV=docs mix inch.report
